create table public.ciudad (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre character varying not null,
  constraint ciudad_pkey primary key (id)
) TABLESPACE pg_default;

create table public.escuelas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre character varying not null,
  cue bigint null,
  anexo bigint null,
  "ciudadId" bigint null,
  constraint escuelas_pkey primary key (id),
  constraint escuelas_ciudadId_fkey foreign KEY ("ciudadId") references ciudad (id)
) TABLESPACE pg_default;

create table public.rol (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre character varying not null,
  constraint rol_pkey primary key (id)
) TABLESPACE pg_default;












create table public.alumnos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null,
  dni character varying null,
  nombre character varying null,
  apellido character varying null,
  asistencia boolean null default false,
  "escuelaId" bigint null,
  email character varying null,
  curso integer null,
  "rolId" bigint not null default '1'::bigint,
  "ciudadId" bigint not null default '1'::bigint,
  constraint alumnos_pkey primary key (id),
  constraint alumnos_escuelaId_fkey foreign KEY ("escuelaId") references escuelas (id) on update RESTRICT on delete RESTRICT,
  constraint alumnos_rolId_fkey foreign KEY ("rolId") references rol (id),
  constraint alumnos_ciudadId_fkey foreign KEY ("ciudadId") references ciudad (id),
  constraint alumnos_curso_check check (
    (
      (curso >= 1)
      and (curso <= 7)
    )
  )
) TABLESPACE pg_default;

ALTER TABLE public.alumnos
ADD COLUMN nombre_completo character varying generated always as (nombre || ' ' || apellido) stored;